/****************************************
 * Name: AccountConstants.cls
 * Description: Constants for Account
 ****************************************/
public without sharing class AccountConstants {

  // AccountTriggerService
  public static final String NAME_PREFIX_SAMPLE = '[サンプル]';

  // AccountTriggerValidation
  public static final String ERROR_MESSAGE_PHONE_REQUIRED = 'FAXが入っている場合は電話番号も入力してください';

}
